# -*- coding: utf-8 -*-
"""Multinomial_Logistic_Regression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QcbBk5CJ6wMuYtKEur-Wp6bOC-i-VB3f
"""

import seaborn as sns
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,confusion_matrix,r2_score
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = sns.load_dataset('iris')

df.head()

encoder = LabelEncoder()
df['species'] = encoder.fit_transform(df['species'])

df = df[['sepal_length','petal_length','species']]

df.head()

X = df.iloc[:,0:2]
y = df.iloc[:,-1]

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=2)

clf = LogisticRegression(multi_class='multinomial', C=0.1, max_iter=100, penalty='l2', solver='sag')

clf.fit(X_train,y_train)

y_pred = clf.predict(X_test)

r2_score(y_pred,y_test)

lr = LogisticRegression(multi_class='multinomial')

lr.fit(X_train,y_train)

y_pred = lr.predict(X_test)
r2_score(y_pred,y_test)

df_test = pd.read_csv('sample_data/mnist_test.csv')
df_train = pd.read_csv('sample_data/mnist_train_small.csv')

df_test

df_train

X_train = df_train.iloc[:,1:].values

y = df_train.iloc[:,0]

df_train.iloc[:,0]

y

X_test = df_test.iloc[:,1:].values

y_test = df_test.iloc[:,0].values

y_test

clf = LogisticRegression(multi_class='multinomial', C=0.01, max_iter=60, solver='sag',penalty='l2')

clf.fit(X_train,y)

y_pred = clf.predict(X_test)

r2_score(y_pred,y_test)

lr = LogisticRegression(multi_class='multinomial')

lr.fit(X_train,y)

y_pred = lr.predict(X_test)

r2_score(y_pred,y_test)

data = pd.read_csv('sample_data/california_housing_train.csv')
data1 = pd.read_csv('sample_data/california_housing_test.csv')

data1.head()

! git init

